/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")
    id("application")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation (files("libs"))
}

tasks.named<Test>("test") {
	useJUnitPlatform()
	testLogging {
		events("passed", "skipped", "failed")
	}
}

application {
    // Define the main class for the application.
    mainClass = "ColorPicker"
}